defmodule RelayAppWeb.ChannelCase do
  @moduledoc """
  Test case for channels. Not generated by phx.new --no-html, so it lives here.
  """

  use ExUnit.CaseTemplate

  using do
    quote do
      import Phoenix.ChannelTest
      import RelayAppWeb.ChannelCase

      @endpoint RelayAppWeb.Endpoint
    end
  end
end
