import AppKit
import Foundation

// S5 probe. Observes NSPasteboard.general and dumps every distinguishing signal
// on each changeCount change. Also writes items the way a BatonPass agent would,
// so agent-written items can be compared against local and UC-delivered ones.

let markerTypes = [
    "com.apple.is-remote-clipboard",
    "com.apple.pasteboard.promised-file-content-type",
    "com.apple.pasteboard.promised-file-url",
    "com.apple.pasteboard.promised-suggested-file-name",
    "org.nspasteboard.TransientType",
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.AutoGeneratedType",
    "org.nspasteboard.IgnoreType",
    "org.nspasteboard.source",
    "org.nspasteboard.ChangeCount",
    "Apple CFPasteboard general",
]

func iso(_ d: Date) -> String {
    let f = ISO8601DateFormatter()
    f.formatOptions = [.withInternetDateTime, .withFractionalSeconds]
    return f.string(from: d)
}

func preview(_ data: Data, limit: Int = 160) -> String {
    if let s = String(data: data, encoding: .utf8), !s.isEmpty,
       s.unicodeScalars.allSatisfy({ $0.value >= 9 }) {
        let t = s.count > limit ? String(s.prefix(limit)) + "…" : s
        return "utf8:" + t.replacingOccurrences(of: "\n", with: "\\n")
    }
    return "hex:" + data.prefix(limit / 2).map { String(format: "%02x", $0) }.joined()
}

func dump(_ pb: NSPasteboard, label: String, previousCount: Int) {
    let cc = pb.changeCount
    print("")
    print("=== \(label) ===")
    print("time            : \(iso(Date()))")
    print("changeCount     : \(cc)   (delta \(cc - previousCount))")
    print("pasteboard.name : \(pb.name.rawValue)")

    let union = pb.types ?? []
    print("pb.types (union, \(union.count)):")
    for (i, t) in union.enumerated() { print("  [\(i)] \(t.rawValue)") }

    let items = pb.pasteboardItems ?? []
    print("pasteboardItems : \(items.count)")

    // Phase A: types only, no data read. A Universal Clipboard item may arrive
    // as a promise; reading data materializes it, so record the shape first.
    for (idx, item) in items.enumerated() {
        print("  [A types-only] item[\(idx)] (\(item.types.count)):")
        for (j, t) in item.types.enumerated() { print("    [\(j)] \(t.rawValue)") }
    }
    print("changeCount after types-only inspection: \(pb.changeCount)")

    // Phase B: read each type's data.
    for (idx, item) in items.enumerated() {
        print("  [B with-data] item[\(idx)] (\(item.types.count)):")
        for (j, t) in item.types.enumerated() {
            let d = item.data(forType: t)
            let n = d?.count ?? -1
            var line = "    [\(j)] \(t.rawValue)  bytes=\(n)"
            if let d = d, n >= 0, n <= 4096 { line += "  \(preview(d))" }
            print(line)
        }
    }
    print("changeCount after data reads: \(pb.changeCount)")

    print("marker probe (explicit reads, independent of the type list):")
    for m in markerTypes {
        let t = NSPasteboard.PasteboardType(m)
        let d = pb.data(forType: t)
        let s = pb.string(forType: t)
        let p = pb.propertyList(forType: t)
        if d == nil && s == nil && p == nil { continue }
        print("    HIT \(m) data=\(d.map { "\($0.count)B \(preview($0))" } ?? "nil") string=\(s ?? "nil") plist=\(String(describing: p))")
    }
    print("  (types above not listed = absent)")

    // Does NSPasteboard expose provenance at all?
    print("provenance surface:")
    print("    NSPasteboard has no public source/owner/origin property (checked at compile time).")
    if #available(macOS 15.4, *) {
        print("    accessBehavior : \(pb.accessBehavior.rawValue)")
    }
    print("=== end \(label) ===")
    fflush(stdout)
}

let pb = NSPasteboard.general
let args = CommandLine.arguments

if args.count > 1 && args[1] == "write" {
    // Case 3: a would-be BatonPass agent writing a received item.
    let payload = args.count > 2 ? args[2] : "batonpass-agent-write"
    let before = pb.changeCount
    pb.clearContents()
    pb.setString(payload, forType: .string)
    print("agent write: changeCount \(before) -> \(pb.changeCount)")
    dump(pb, label: "AGENT-WRITTEN (case 3)", previousCount: before)
    exit(0)
}

if args.count > 1 && args[1] == "write-marked" {
    // Variant: agent write that also stamps org.nspasteboard.source, to see
    // whether a self-stamp survives and whether it is visible to readers.
    let payload = args.count > 2 ? args[2] : "batonpass-agent-write-marked"
    let before = pb.changeCount
    pb.clearContents()
    let item = NSPasteboardItem()
    item.setString(payload, forType: .string)
    item.setString("co.subvisual.batonpass", forType: NSPasteboard.PasteboardType("org.nspasteboard.source"))
    pb.writeObjects([item])
    print("agent marked write: changeCount \(before) -> \(pb.changeCount)")
    dump(pb, label: "AGENT-WRITTEN-MARKED (case 3b)", previousCount: before)
    exit(0)
}

if args.count > 1 && args[1] == "write-localonly" {
    // The mechanism that keeps an agent write off Universal Clipboard:
    // prepareForNewContentsWithOptions(.currentHostOnly) (AppKit 10.12+).
    let payload = args.count > 2 ? args[2] : "batonpass-localonly"
    let before = pb.changeCount
    print("option rawValue: \(NSPasteboard.ContentsOptions.currentHostOnly.rawValue)")
    let returned = pb.prepareForNewContents(with: [.currentHostOnly])
    print("prepareForNewContents returned changeCount: \(returned)")
    let ok = pb.setString(payload, forType: .string)
    print("setString ok: \(ok)")
    print("local-only write: changeCount \(before) -> \(pb.changeCount)")
    dump(pb, label: "AGENT-WRITTEN-LOCAL-ONLY", previousCount: before)
    exit(0)
}

if args.count > 1 && args[1] == "once" {
    dump(pb, label: "SNAPSHOT", previousCount: pb.changeCount)
    exit(0)
}

var last = pb.changeCount
print("pbprobe watching NSPasteboard.general — initial changeCount \(last)")
dump(pb, label: "INITIAL", previousCount: last)
fflush(stdout)

while true {
    let cc = pb.changeCount
    if cc != last {
        dump(pb, label: "CHANGE", previousCount: last)
        last = cc
    }
    usleep(80_000)
}
