defmodule RelayAppWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :relay_app

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_relay_app_key",
    signing_salt: "vCtoGX2y",
    same_site: "Lax"
  ]

  # socket "/live", Phoenix.LiveView.Socket,
  #   websocket: [connect_info: [session: @session_options]],
  #   longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  # Binary frames only; the relay never interprets them. CONTRACT.md §1.
  socket "/socket", RelayAppWeb.ClipboardSocket,
    websocket: [connect_info: [:peer_data], max_frame_size: 65_597],
    longpoll: false

  plug Plug.Static,
    at: "/",
    from: :relay_app,
    gzip: not code_reloading?,
    only: RelayAppWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug RelayAppWeb.Router
end
