import Config

bind_ip_string = System.get_env("BATONPASS_BIND_IP", "127.0.0.1")

bind_ip =
  case :inet.parse_address(String.to_charlist(bind_ip_string)) do
    {:ok, ip} ->
      ip

    {:error, reason} ->
      raise "invalid BATONPASS_BIND_IP #{inspect(bind_ip_string)}: #{inspect(reason)}"
  end

allowed_stable_ids =
  System.get_env("BATONPASS_ALLOWED_STABLE_IDS", "")
  |> String.split(",", trim: true)
  |> Enum.map(&String.trim/1)
  |> Enum.reject(&(&1 == ""))

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :relay_app, RelayAppWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  # Tailnet interface only, never 0.0.0.0. CONTRACT.md §2.
  http: [ip: bind_ip],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  # The fallback is for loopback-only development. Any hosted instance must
  # supply a persistent, untracked value through SECRET_KEY_BASE.
  secret_key_base:
    System.get_env(
      "SECRET_KEY_BASE",
      "pe5NzWM+btgQc8IzLZ/YWf5khKTCU99qUNRKnWhE6MU4TuyJb5nwYFMqyGY69t3v"
    ),
  watchers: []

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :relay_app, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Instance-specific identity and enrollment data must never be committed. Empty
# values fail closed: no owner or device can pass the gate.
config :relay_app,
  tailscale_bin: System.get_env("BATONPASS_TAILSCALE_BIN", "/usr/bin/tailscale"),
  owner_login: System.get_env("BATONPASS_OWNER_LOGIN", ""),
  allowed_stable_ids: allowed_stable_ids
